name: "andres_dbt"
version: "1.0.0"
config-version: 2

profile: "bigquery"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  andres_dbt:
    materialized: table

seeds:
  +schema: source_data
  andres_dbt:
    custom: # For  testing porpouse  adding new seed
      +enabled: false 


vars:
  sources_list:
    - twitter
    - tiktok
    - bing
    - facebook
  remap_fields:
    tiktok:
      total_conversions: conversions + skan_conversion
    bing:
      total_conversions: conv
    facebook:
      total_conversions:
        purchase
        # engagements: likes + shares + shares_2 + comments + comments_2 + views + views_2 + clicks + clicks_2
      engagements: likes + shares +  comments +  views +  clicks
# for adding a new resource
    # custom:
    #   total_conversions: conver

