default:

bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: improvado-387515
      dataset: public
      location: US
      keyfile: "{{ env_var('JSON_FILE') }}"


