sources:
  - name: source_defined_data
    schema: public_source_data
    tables:
      - name: mcdm
        identifier: mcdm_paid_ads_basic_performance_structure
  - name: source_data
    schema: public_source_data
    tables:
      - name: bing
        identifier: src_ads_bing_all_data
        columns:
          - name: channel
            tests:
              - dbt_expectations.expect_column_to_exist
          - name: date
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null
              - dbt_expectations.expect_column_values_to_be_in_type_list:
                  column_type_list: [date, datetime]
      - name: facebook
        identifier: src_ads_creative_facebook_all_data
        columns:
          - name: channel
            tests:
              - dbt_expectations.expect_column_to_exist
          - name: date
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null
              - dbt_expectations.expect_column_values_to_be_in_type_list:
                  column_type_list: [date, datetime]

      - name: tiktok
        identifier: src_ads_tiktok_ads_all_data
        columns:
          - name: channel
            tests:
              - dbt_expectations.expect_column_to_exist
          - name: date
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null
              - dbt_expectations.expect_column_values_to_be_in_type_list:
                  column_type_list: [date, datetime]

      - name: twitter
        identifier: src_promoted_tweets_twitter_all_data
        columns:
          - name: channel
            tests:
              - dbt_expectations.expect_column_to_exist
          - name: date
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null
              - dbt_expectations.expect_column_values_to_be_in_type_list:
                  column_type_list: [date, datetime]

      # For adding new resources
      - name: custom  
        identifier: src_custom
        columns:
          - name: channel
            tests:
              - dbt_expectations.expect_column_to_exist
          - name: date
            tests:
              - dbt_expectations.expect_column_to_exist
              - not_null
              - dbt_expectations.expect_column_values_to_be_in_type_list:
                  column_type_list: [date, datetime]
